package com.vehicle.rental.dto.response;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Generic Data Transfer Object for wrapping API responses.
 * Provides a consistent JSON structure for the frontend, typically containing
 * a human-readable success/error message and the actual requested payload.
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
public class ApiResponse {

    /**
     * A human-readable message providing context about the API operation's result
     * (e.g., "Registration successful", "Vehicle updated successfully").
     */
    private String message;

    /**
     * The actual data payload requested by the client or generated by the server.
     * This can be a JWT token, a specific DTO, a list of objects, or null if the
     * operation only requires a status message.
     */
    private Object data;
}