package com.vehicle.rental.config;

import com.vehicle.rental.entity.User;
import com.vehicle.rental.repository.UserRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.CommandLineRunner;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Component;

@Slf4j
@Component
@RequiredArgsConstructor
public class AdminInitializer implements CommandLineRunner {

    private final UserRepository userRepository;
    private final PasswordEncoder passwordEncoder;

    @Override
    public void run(String... args) {
        // Check if Admin already exists so we don't create duplicates
        if (userRepository.findByEmail("admin@vehicle.com").isEmpty()) {
            log.info("No Admin found. Creating default system administrator...");

            User admin = new User();
            admin.setName("System Admin");
            admin.setEmail("admin@vehicle.com");
            // This ensures the hash is generated by YOUR encoder
            admin.setPassword(passwordEncoder.encode("admin123"));
            admin.setRole(User.Role.ADMIN); // Make sure this matches your User.Role enum

            userRepository.save(admin);
            log.info("Default Admin created with password: admin123");
        } else {
            log.info("Admin account already exists. Skipping initialization.");
        }
    }
}